21 add destination field to header and support versioning in packets
VIP-LES/EosLib pull request #23
Opened 2022-11-12 18:43 UTC by thomasmholder

I think this would bring us to version 0.1.1, I need to remember to set that in setup.py before merging.

2022-11-12 19:42 UTC, thomasmholder commented
Actually thinking more about it, it should probably be 0.2.0

2022-11-13 05:45 UTC, DarylDohner requested changes
Overall good, see comments
Also agreed that this should become 0.2.0

2022-11-13 05:45 UTC, DarylDohner commented on EosLib/packet/definitions.py
> +    TRANSMIT = 4
Did both data and transmit headers change?  Looks to me like only the data header did

2022-11-13 05:45 UTC, DarylDohner commented on EosLib/packet/data_header.py
> +        elif header_bytes[0] in old_data_headers:
This case is not reachable -- need to switch the order

2022-11-13 05:45 UTC, DarylDohner commented on EosLib/packet/data_header.py
> +            raise PacketFormatError("Created by an incompatible version of EosLib")
Is there a better way we could handle this case?  This should be a recoverable scenario.  I feel like we could use a factory pattern to process the data based on the preamble number

2022-11-13 05:45 UTC, DarylDohner commented on EosLib/packet/data_header.py
> +        elif header_bytes[0] in old_data_headers:
also should add tests for the old header execution paths

2022-11-13 05:45 UTC, DarylDohner commented on EosLib/packet/definitions.py
> +                                   "d"
What was the motivation for moving these?  They are specific to their headers, should they not live in the classes for those headers?  Imo these should be `TransmitHeader.format_string` and `DataHeader.format_string`, better for organization / not having messy imports

2022-11-13 05:45 UTC, DarylDohner commented on EosLib/packet/data_header.py
> +        if not isinstance(self.destination, int) or not 0 <= self.destination <= 255:
Maybe we should define a validator module for struct native data types.  These could be `validate_uint8(self.priority)` etc

2022-11-13 19:48 UTC, thomasmholder commented on EosLib/packet/definitions.py
> +                                   "d"
Previously I agreed with that, but I decided that having the maximum allowed body size exposed would be good for backwards compatibility, and to put that in definitions we would have to import TransmitHeader/DataHeader in definitions which is a circular import. We could move the maximum body size to Packet as well, but this was the first solution that came to mind.

2022-11-13 19:49 UTC, thomasmholder commented on EosLib/packet/definitions.py
> +    TRANSMIT = 4
Agreed

2022-11-13 19:53 UTC, thomasmholder commented on EosLib/packet/data_header.py
> +        if not isinstance(self.destination, int) or not 0 <= self.destination <= 255:
Agreed, but low priority. Added to #18

2022-11-13 19:54 UTC, thomasmholder commented on EosLib/packet/data_header.py
> +            raise PacketFormatError("Created by an incompatible version of EosLib")
I agree, but this is going to result in a lot of duplicate code. I've added this to #18 so we can figure out a good way to handle that.

2022-11-13 20:09 UTC, thomasmholder commented on EosLib/packet/definitions.py
> +    TRANSMIT = 4
Fixed

2022-11-13 20:09 UTC, thomasmholder commented on EosLib/packet/data_header.py
> +        elif header_bytes[0] in old_data_headers:
Fixed

2022-11-13 21:29 UTC, DarylDohner requested changes

2022-11-13 21:29 UTC, DarylDohner commented on EosLib/packet/definitions.py
> +                                   "d"
All of these values are associated with specific classes though, which merits them being class constants instead of in the definitions.py, which ideally only contains things that belong to the package but don't pertain to any other specific class/module within the package
data_header_struct_format_string => DataHeader.format_string
transmit_header_struct_format_string => TransmitHeader.format_string
BODY_MAX_BYTES => Packet.body_max_bytes
RADIO_MAX_BYTES => Packet.size
I think it also may be useful to define DataHeader.size and TransmitHeader.size

2022-11-13 21:57 UTC, thomasmholder commented on EosLib/packet/definitions.py
> +                                   "d"
I went ahead and moved everything, though I don't see why we would need DataHeader.size and TransmitHeader.size

2022-11-13 22:00 UTC, DarylDohner approved these changes

2022-11-14 19:03 UTC, merged