#37 updated pytest version in requirements.txt
VIP-LES/EosLib pull request #39
Opened 2023-02-06 22:21 UTC by aryanbattula

- I updated he requirements to have pytest version 7.2.1.

2023-02-10 18:42 UTC, thomasmholder commented
Ok I lied, we don't need to update the version number, go ahead and re-request review and I'll approve it.

2023-02-14 04:27 UTC, DarylDohner requested changes

2023-02-14 04:27 UTC, DarylDohner commented on requirements.txt
>  py==1.11.0
need to remove py==1.11.0

2023-02-27 17:34 UTC, DarylDohner commented
@aryanbattula you good?

2023-02-28 17:40 UTC, DarylDohner requested changes
Looks like you still gotta do 2 things:

1.  add your name to contributors.md
2. you got a merge conflict you gotta resolve, lmk if you need help with this

2023-02-28 22:55 UTC, thomasmholder commented
Looks good to me, @DarylDohner anything else?

2023-02-28 22:55 UTC, thomasmholder approved these changes

2023-02-28 23:50 UTC, DarylDohner approved these changes

2023-03-02 19:58 UTC, merged