36_expand_device_list
VIP-LES/EosLib pull request #40
Opened 2023-02-07 15:40 UTC by cjkerr128

doubled size of misc. device space, new sensors to be flown the semester, and SPOT and ARPS

2023-02-08 14:22 UTC, thomasmholder requested changes
This looks really good, but I think we could go ahead and add a bunch of MISC_TEST IDs, as we seem to go through those pretty quickly. 

We also need to bump the versioning, I think this could arguably be either a minor or major version, depending on how the validators work.

2023-02-08 15:56 UTC, thomasmholder commented
Oh, and before I forget, APRS should have an APRS_API and an APRS_DEVICE (or something along those lines) ID, as both of those are valid but distinct sources.

2023-02-10 18:40 UTC, thomasmholder commented
Don't worry about the versioning, just add the other stuff and you're good to go.

2023-04-02 20:18 UTC, thomasmholder approved these changes
Looks good to me

2023-04-02 20:26 UTC, DarylDohner requested changes
see comment

2023-04-02 20:26 UTC, DarylDohner commented on EosLib/device.py
> +    APRS_API = 57
This duplicates ARPS_API = 37

2023-04-02 20:28 UTC, DarylDohner approved these changes

2023-04-02 20:29 UTC, merged