#33 add pytest parameterize/fixture & organize tests
VIP-LES/EosLib pull request #43
Opened 2023-02-08 06:02 UTC by VanL15

2023-02-08 15:54 UTC, thomasmholder requested changes
This looks really good, I left one tiny comment about an idea I had for improving it further, and we need to bump the version number (this is a patch I think).

2023-02-08 15:54 UTC, thomasmholder commented on tests/packet/test_packet.py
> +def test_validate_good_transmit_header(packet):
It might be worth parametrizing the validate_good tests, probably with a list of all the Devices, Priorities, etc.  You can also stack parametrizations and it'll iterate over both lists, which might be worthwhile even if it makes lots of tests.

2023-02-15 19:46 UTC, VanL15 commented
I parameterized the test_validate_good_data_header test with all the different devices, priorities, and packet types. I don't believe the good_transmit_header test can be parameterized in the same way because the transmit_header validation only checks for the sequence number and the send time, neither of which are enums which can be iterated over. I also bumped the patch number up, going from '1.0.0' to '1.0.1'.

2023-02-16 04:19 UTC, thomasmholder requested changes
This looks great (even though it makes a kinda comical amount of tests)! The only other thing I forgot to mention is to add your name to CONTRIBUTORS.md. Do that real quick and re-request review and I'll approve it

2023-02-16 05:01 UTC, VanL15 commented
Added my name to CONTRIBUTORS.md.

2023-02-16 17:38 UTC, DarylDohner requested changes

2023-02-16 17:38 UTC, DarylDohner commented on tests/packet/test_packet.py
> +@pytest.mark.parametrize("priority", definitions.Priority)
This is the right motive but not quite the correct execution.  This generates n * m * k tests, which comes out to like ~1500 rn, and it's not incredibly useful.  What you're trying to test is that all devices, types, priorities are in-bounds for the data width limitations in the packet right?  The way to do that would be to have those enums include auto-validation for the data widths.

Alternately, you could just use take the min, max, and happy path enum values here

2023-02-18 01:40 UTC, DarylDohner requested changes
Close, see comments

2023-02-18 01:40 UTC, DarylDohner commented on setup.py
> +      version='1.0.1',
i don't think incrementing the version is justified for this ticket which is just refactoring tests

2023-02-18 01:42 UTC, DarylDohner commented on tests/packet/test_packet.py
> +@pytest.mark.parametrize("sender", [1, len(definitions.Device) - 1, 14])
Oops -- one of my review comments wasn't saved

Enums do not guarantee that the values are contiguous and tracking the array index. Also we should be programmatically computing min and max.  I would suggest using min(definitions.Device), max(), and then picking an arbitrary device from the list (ie, Device.MISC_1) -- no integer literals

This applies to the rest of the parametrize() calls too

2023-02-20 22:55 UTC, VanL15 commented
For the test_validate_good_data_header_sender() test, I couldn't use the min value of the enum since it is NO_DEVICE, so I used the device closest to the min. If that is wrong or I should change it to something else, let me know.

2023-02-21 00:07 UTC, DarylDohner approved these changes

2023-02-21 05:43 UTC, thomasmholder approved these changes

2023-02-21 16:46 UTC, merged