44 add rssi transmit header
VIP-LES/EosLib pull request #45
Opened 2023-02-17 17:17 UTC by aryanbattula

-Added RSSI to transmit header
- changed tests as well

2023-02-20 21:05 UTC, aryanbattula commented
- I fixed most of the tests but I had a couple that were giving me trouble.
- Since I have other tickets that rely on this one, I will push this for now and start the other tickets
-

2023-02-22 14:24 UTC, thomasmholder requested changes
Looks pretty good, a lot of tiny style changes and a couple logical changes, you need to add tests that test the min/max values of RSSI because right now 0 is the only value that will work.

2023-02-22 14:24 UTC, thomasmholder commented on EosLib/packet/definitions.py
> +
Why the added whitespace?

2023-02-22 14:24 UTC, thomasmholder commented on EosLib/packet/packet.py
> +
Also why this extra whitespace?

2023-02-22 14:24 UTC, thomasmholder commented on EosLib/packet/packet.py
> +            print(packet_bytes[0:struct.calcsize(TransmitHeader.transmit_header_struct_format_string)])
Are these debugging statements you forgot to remove?

2023-02-22 14:24 UTC, thomasmholder commented on EosLib/packet/packet.py
>          if packet_bytes[0] == HeaderPreamble.TRANSMIT:
Because we're updating the struct format you actually need to increment HeaderPreamble.TRANSMIT and add the old version to the old array

2023-02-22 14:24 UTC, thomasmholder commented on EosLib/packet/transmit_header.py
> +                                           "d" \
The last character here doesn't need a \

2023-02-22 14:24 UTC, thomasmholder commented on EosLib/packet/transmit_header.py
> +        if not isinstance(self.send_rssi, int) or not -120 <= self.send_rssi <= 0:
You're encoding rssi to a single unsigned byte, this range isn't valid.

2023-02-22 14:24 UTC, thomasmholder commented on EosLib/packet/transmit_header.py
> +                                                                send_rssi=self.send_rssi,
Indentation here isn't quite right

2023-02-22 14:24 UTC, thomasmholder commented on tests/packet/test_packet.py
> +
Why?

2023-02-22 14:24 UTC, thomasmholder commented on tests/packet/test_packet.py
> +#check this stuff out
What stuff?

2023-02-22 14:24 UTC, thomasmholder commented on tests/packet/test_packet.py
> +
Why so much new whitespace

2023-02-24 19:39 UTC, thomasmholder requested changes
Worlds tiniest changes and you're good to go.

2023-02-24 19:39 UTC, thomasmholder commented on EosLib/packet/transmit_header.py
> +                 send_rssi: int,
If you change send_rssi to be last in the constructor and add a default value, I don't think this change will break the API, which would be good. You can use right click->refactor->change signature in pycharm to do this automatically.

2023-02-24 19:39 UTC, thomasmholder commented on tests/packet/test_packet.py
> +def test_min_max_transmit_header(packet, rssi):
Should mention RSSI in this test name

2023-02-24 19:44 UTC, thomasmholder commented
Also please get in the habit of using descriptive commit messages

2023-02-27 03:46 UTC, thomasmholder requested changes
This is bordering on a nitpick, but address my one comment and this looks good to approve.

2023-02-27 03:46 UTC, thomasmholder commented on EosLib/packet/transmit_header.py
> +    def __init__(self, send_seq_num: int, send_rssi: int = -120, send_time: datetime = None):
By convention we've been using 0 as default values, we should probably stick to that here. Also, I'm not sure it actually matters for anything we've written so far, but it would be ideal to re-order the constructor so rssi is last. You can do it super easily with the change signature option in pycharm, you just select the value and then use the little arrows.

2023-02-28 22:53 UTC, thomasmholder commented
Fix merge conflicts

2023-03-03 20:23 UTC, thomasmholder approved these changes
Looks good to me

2023-03-03 20:32 UTC, merged