#46 Telemetry Format Class
VIP-LES/EosLib pull request #47
Opened 2023-03-01 21:40 UTC by IonLi09

Used telemetry driver data provided by David to create a format class for telemetry data

v1.1?

2023-03-01 21:41 UTC, IonLi09 commented
David added the test code

2023-03-02 23:05 UTC, David-Rey requested changes
Add some comments to what things do and add the decode function to the test function

2023-03-03 20:27 UTC, thomasmholder commented on tests/telemetryData/test_telemetryData.py
> +import pytest
by convention, this should follow the structure of the EosLib module, so it should be tests/format/test_TelemetryData (though file names should also be lowercase and separated by _s)

2023-03-03 22:51 UTC, IonLi09 commented on tests/telemetryData/test_telemetryData.py
> +import pytest
Resolved

2023-03-04 02:06 UTC, thomasmholder requested changes
Looks good so far, I left a good number of comments with changes, some of them are just style but I had some questions about logic/use as well. The main things that need to be done are fixing/implementing the tests, and adding info (including units) to the readme.

2023-03-04 02:06 UTC, thomasmholder commented on EosLib/format/TelemetryData.py
> +    # Initialize data to params (default values otherwise)
These comments explaining functions should all be docstrings instead, see [here](https://www.dataquest.io/blog/documenting-in-python-with-docstrings). By convention, we use the reStructuredText format.

2023-03-06 16:06 UTC, thomasmholder requested changes
I know there are a lot of comments, but this is an excellent update on your part, the only things left are some things that are either for consistency with the rest of the library or nitpicks.

As a note, you do need to merge main before the tests will run on github, so if you have conflicts it's a good habit to get into fixing them before requesting review.

2023-03-06 16:06 UTC, thomasmholder commented on EosLib/format/telemetry_data.py
> +    def __init__(self, timestamp: float = datetime.now(), temperature: float = float("NaN"), pressure: float = float("NaN"), humidity: float = float("NaN"),
This line is also a little too long if you don't mind breaking it up, it should end up as three pretty even lines

2023-03-06 16:21 UTC, thomasmholder commented on EosLib/format/telemetry_data.py
> +    :type timestamp: DATETYPE
One more quick note, if you have type annotations in the signature, you don't need to specify in the docstring (and should probably remove it where you do because it's redundant)

2023-03-08 20:19 UTC, thomasmholder commented
Looks good to me, go ahead and pull it in as is, I'm going to make another ticket to fix a couple style issues and bump the version number.

2023-03-08 20:19 UTC, thomasmholder approved these changes

2023-03-11 01:09 UTC, David-Rey approved these changes
lgtm

2023-03-11 01:10 UTC, merged