Refactored decode position and made position test
VIP-LES/EosLib pull request #54
Opened 2023-04-07 17:39 UTC by IonLi09

We added test_position.py

2023-04-07 17:48 UTC, David-Rey submitted a review, later dismissed
lgtm

2023-04-07 18:31 UTC, DarylDohner requested changes
See comments.  You also need to update setup.py to bump the version to 2.0.1

2023-04-07 18:31 UTC, DarylDohner commented on tests/format/test_position.py
> +# import EosLib
remove unnecessary line

2023-04-07 18:31 UTC, DarylDohner commented on EosLib/format/position.py
>          if isinstance(gps_packet, Packet):
Line 53 is wrong, position has no property called gps_packet
I think you just want `gps_packet.data_header.data_type`

2023-04-07 18:31 UTC, DarylDohner commented on tests/format/test_position.py
> +def test_position():
you also need to test the flow where decode_position takes a Packet as the parameter

2023-04-11 19:35 UTC, DarylDohner requested changes
You forgot to address  this: **You also need to update setup.py to bump the version to 2.0.1**

2023-04-11 19:35 UTC, DarylDohner commented on tests/format/test_position.py
> +    assert decoded_new_data.valid
need newline at end of file

2023-04-11 19:35 UTC, DarylDohner commented on tests/format/test_position.py
> +    assert 23.4 == decoded_new_data.latitude
make all the numbers different, if you use the same numbers then you wouldn't know if they got accidentally switched somehow

2023-04-11 19:35 UTC, DarylDohner commented on tests/format/test_position.py
> +
add docstring

2023-04-12 10:42 UTC, DarylDohner approved these changes
Approved, tag new version (2.0.1) after merge

2023-04-12 16:55 UTC, merged