57 abstract format class
VIP-LES/EosLib pull request #58
Opened 2023-06-07 20:42 UTC by thomasmholder

2023-06-11 04:03 UTC, DarylDohner commented on EosLib/format/decode_factory.py
> +        return self._decoders[data_format](data)
feel like there should be a check here for if someone tries to decode an unrecognized type to give a more comprehensible error than KeyError

2023-06-12 03:27 UTC, DarylDohner requested changes
I really like it, just got some minor review comments for you

2023-06-12 03:27 UTC, DarylDohner commented on example.py
the below example code is no longer valid (raw bytes are no longer a valid packet body)

2023-06-12 03:27 UTC, DarylDohner commented on tests/packet/test_packet.py
> +class MockFormat(EosLib.format.base_format.BaseFormat):
idk, i think this could probably be exposed in EosLib.format.formats, could have uses for other tests like radio or mqtt tests

2023-06-12 03:27 UTC, DarylDohner commented on tests/packet/test_packet.py
> +decode_factory.register_decoder(MockFormat)
shouldnt the __init_subclass__ already handle this?

2023-06-12 03:27 UTC, DarylDohner commented on tests/format/test_position.py
missing coverage for Position.get_validity()

2023-06-12 03:27 UTC, DarylDohner commented on tests/format/test_telemetry_data.py
> +class TestEQ:
This class is all dupe code, it should be genericized.  I'd suggest making a TestFormat class that the format tests can extend that has built-in default testing behavior

2023-06-12 03:27 UTC, DarylDohner commented on tests/format/test_telemetry_data.py
> +
also missing coverage for get_validity

2023-06-12 22:08 UTC, thomasmholder commented on EosLib/packet/packet.py
> +    def __init__(self, body: BaseFormat, data_header: DataHeader, transmit_header: TransmitHeader = None):
If there is any legitimate use case for this someone can write a packet wrapper format.

Also, we would have to start handling radio_max_bytes dynamically and that sounds un-fun.

2023-06-12 22:09 UTC, thomasmholder commented on EosLib/packet/data_header.py
> +                 data_type: EosLib.format.definitions.Type = EosLib.format.definitions.Type.NO_TYPE,
This is a side effect of moving Type from EosLib.packet to EosLib.format

2023-06-12 22:17 UTC, thomasmholder commented on EosLib/format/decode_factory.py
> +        return self._decoders[data_format](data)
Added

2023-06-12 22:23 UTC, thomasmholder commented on tests/packet/test_packet.py
> +class MockFormat(EosLib.format.base_format.BaseFormat):
Moved

2023-06-12 22:38 UTC, DarylDohner commented on EosLib/packet/data_header.py
> +                 data_type: EosLib.format.definitions.Type = EosLib.format.definitions.Type.NO_TYPE,
`from EosLib.format.definitions import Type`

2023-06-14 14:38 UTC, thomasmholder commented on EosLib/packet/packet.py
> +        decoded_packet = Packet(EosLib.format.decode_factory.decode_factory.decode(data_type,
Removed Encode and Decode to/from string

2023-06-14 15:22 UTC, thomasmholder commented on tests/format/test_position.py
Added

2023-06-14 15:22 UTC, thomasmholder commented on tests/format/test_telemetry_data.py
> +
Added

2023-06-14 15:33 UTC, thomasmholder commented on example.py
Fixed

2023-06-17 12:47 UTC, DarylDohner requested changes

2023-06-22 00:15 UTC, thomasmholder commented on tests/format/formats/test_empty_format.py
> +        return []
This is tested implicitly elsewhere, added an explicit test

2023-06-22 00:16 UTC, thomasmholder commented on EosLib/format/formats/empty_format.py
> +        self.num_bytes = num_bytes
Done

2023-06-22 00:28 UTC, thomasmholder commented on tests/format/formats/format_test.py
> +    def get_good_format(self):
I added comments, if that's not enough, if you have suggestions for better names (or a better way to do this generally) i'm all ears

2023-06-22 00:28 UTC, thomasmholder commented on tests/format/formats/format_test.py
> +        for i in range(len(self.get_good_format_list())):
Added

2023-06-22 00:28 UTC, thomasmholder commented on EosLib/format/formats/empty_format.py
> +        return struct.pack(self.get_format_string())
Yes

2023-06-22 00:29 UTC, thomasmholder commented on EosLib/format/formats/empty_format.py
> +class EmptyFormat(BaseFormat):
Added a docstring. All of this needs better documentation long term, but I want to get the version of EosLib that's going to be flown soon released ASAP

2023-06-22 00:29 UTC, thomasmholder commented on EosLib/format/decode_factory.py
> +        if issubclass(format_class, csv_format.CsvFormat):
Done

2023-06-22 11:56 UTC, DarylDohner requested changes
tiny tiny things

2023-06-22 11:56 UTC, DarylDohner commented on EosLib/__init__.py
> +from EosLib.packet.definitions import Priority
This is...strange, right?  Why is Priority here, of all things?

2023-06-22 11:56 UTC, DarylDohner commented on EosLib/format/base_format.py
> +    def get_decoders(cls) -> {}:
I think the actual return type here is `dict[type, callable]`

2023-06-22 11:56 UTC, DarylDohner commented on EosLib/format/formats/empty_format.py
> +class EmptyFormat(BaseFormat):
This will be 4.0.0 but that will almost certainly not be the version that's flown, I have at least 4 formats to add after this is merged & also david has an outstanding EosLib ticket (which may or may not get done)

2023-06-22 11:56 UTC, DarylDohner commented on tests/format/formats/format_test.py
> +    def get_good_format(self):
get_good_format_list => get_good_format_params
get_format_from_list => remove, just invoke the constructor directly.  Using splat operators avoids the need for something like get_position_from_list
get_good_format => maybe keep as sugar/shorthand, but also could just invoke the ctor directly

2023-06-22 11:56 UTC, DarylDohner commented on EosLib/format/decode_factory.py
> +from EosLib.format import csv_format
unused import

2023-06-23 04:16 UTC, thomasmholder commented on EosLib/__init__.py
> +from EosLib.packet.definitions import Priority
No idea

2023-06-23 04:16 UTC, thomasmholder commented on EosLib/format/base_format.py
> +    def get_decoders(cls) -> {}:
Correct

2023-06-23 04:16 UTC, thomasmholder commented on EosLib/format/decode_factory.py
> +from EosLib.format import csv_format
Removed

2023-06-23 04:47 UTC, DarylDohner approved these changes

2023-06-24 00:00 UTC, merged