#65 create cutdown command format
VIP-LES/EosLib pull request #67
Opened 2023-09-29 00:12 UTC by IonLi09

We created a cutdown command format by packetizing the data and wrote encode and decode methods to write to csv format.

2023-09-29 00:38 UTC, DarylDohner requested changes
good first start but see comments

2023-09-29 00:38 UTC, DarylDohner commented on EosLib/format/formats/cutdown.py
> +class CutDown(CsvFormat):
probably doesn't need to be CSV-serializable since it's only ever transmitted and never logged to a csv file like data would be

2023-09-29 00:38 UTC, DarylDohner commented on EosLib/format/formats/cutdown.py
> +                 time: datetime.datetime.now(),
so formats get encoded into packets, which include headers that already cover these metadata fields, so you don't need them here -- check out the data header and transmit header in EosLib.packet

2023-09-29 00:38 UTC, DarylDohner commented on EosLib/format/formats/cutdown.py
> +                 body: float = None):
what is body?  like i can see its a float but what's the significance?

2023-09-29 00:38 UTC, DarylDohner commented on EosLib/format/formats/cutdown.py
> +        :param z_rotation: The z rotation data
hmmm copy paste hmmm

2023-09-29 00:38 UTC, DarylDohner commented on tests/format/formats/test_cutdown.py
> +good_data_list = [datetime.datetime.now(), 1, 2, 3, 4, 5]
should probably use a float value to test float params

2023-09-29 00:38 UTC, DarylDohner commented on EosLib/format/formats/cutdown.py
> +                 body: float = None):
as i said on friday i feel that a sufficient format could just be a single field: sequence number
(whether it is a command or response is already encoded in the header field for format type, see [here](https://github.com/VIP-LES/EosLib/blob/main/EosLib/format/definitions.py))

2023-09-29 00:38 UTC, DarylDohner commented on EosLib/format/README.md
> +`Sender`, `Packet Type`, `Priority`, `Destination`, and `Body` are enums.
this is like sort of false on 2 counts
1) based on your constructor those should be floats not ints
2) you did not say what the enums are

2023-10-02 13:42 UTC, thomasmholder requested changes
Looks alright, still some changes needed

2023-10-02 13:42 UTC, thomasmholder commented on EosLib/format/README.md
> +`Ack` is an acknowledgement for the payload receiving our command, incrementing for each command sent.
The implementation here could be clearer, is the plan for the payload to echo the command or something else?

2023-10-02 13:42 UTC, thomasmholder commented on EosLib/format/formats/cutdown.py
> +class CutDown:
This should still extend BaseFormat

2023-10-02 13:42 UTC, thomasmholder commented on tests/format/formats/test_cutdown.py
> +from EosLib.format.formats.cutdown import CutDown
What happened to the Check class? That's what was running the actual tests, these don't actually do any testing of encode/decode

2023-10-02 19:36 UTC, thomasmholder requested changes
Looks good, you just need to add a value to the Type enum in definitions.py

2023-10-03 18:27 UTC, thomasmholder submitted a review, later dismissed
Looks good to me

2023-10-04 15:33 UTC, DarylDohner commented
> Looks good, you just need to add a value to the Type enum in definitions.py

^^ this was incorrect, we should use the COMMAND type for it

2023-10-04 16:00 UTC, DarylDohner requested changes
almost done!
- remove CUTDOWN type
- version tag as 4.0.2 in setup.py
- wait for EosLib#69 to be merged before merging

2023-10-13 17:12 UTC, thomasmholder approved these changes
Looks good to me

2023-10-13 17:17 UTC, thomasmholder submitted a review, later dismissed
I lied, you need to re-add the CUTDOWN type to definitions.py and change the type in CutDown

2023-10-23 18:36 UTC, DarylDohner requested changes
a couple tiny things, see comments

2023-10-23 18:36 UTC, DarylDohner commented on setup.py
> +      version='4.0.2',
4.0.1

2023-10-23 18:36 UTC, DarylDohner commented on EosLib/format/formats/cutdown.py
> +        return "Command sent: ACK " + str(self.ack)
got it backwards, should be "received cutdown ack: ##"

2023-10-23 18:58 UTC, merged