#68 add format types for responses
VIP-LES/EosLib pull request #69
Opened 2023-10-03 19:19 UTC by VanL15

- Created the format types for the responses of the ping and cutdown commands
- Implemented it with two enum values of "RESPONSE_START" and "RESPONSE_END", with all valid response types in between. If many more responses get added in the future, it will be easier to check if a packet received is a response by checking if it is between "RESPONSE_START" and "RESPONSE_END", rather than having a very long OR statement.
- Made the value of the responses start at 32, so that we leave space for other types below it if necessary.
- New version number: 4.0.1

2023-10-03 19:24 UTC, VanL15 commented
Should I have decremented the TELEMETRY_DATA and EMTPY values? (Since I removed the RESPONSE value)

2023-10-04 15:49 UTC, DarylDohner requested changes
see comments

2023-10-04 15:49 UTC, DarylDohner commented on EosLib/format/definitions.py
>      COMMAND = 5
should also have command_start and end

2023-10-04 15:49 UTC, DarylDohner commented on EosLib/format/definitions.py
> +    CUTDOWN_RESPONSE = 34
these hardcoded types for ping and cutdown kill the genericness factor here.  either remove them or have them both = response_start

2023-10-20 17:27 UTC, closed without merging

2023-10-20 17:27 UTC, aryanbattula commented
Is not needed anymore