added ping format
VIP-LES/EosLib pull request #75
Opened 2023-11-01 04:21 UTC by aryanbattula

- created ping format
- created tests to format
- added Ping to Type

2023-11-01 17:37 UTC, DarylDohner requested changes
see comments.  also you need to pick a version number (4.1.0 i guess) and update setup.py

2023-11-01 17:37 UTC, DarylDohner commented on EosLib/format/definitions.py
> +    PING_ACK = 10
why not name it just PING?

2023-11-01 17:37 UTC, DarylDohner commented on tests/format/formats/test_ping_format.py
> +    assert good_sender_data.to_terminal_output_string() == "Received Ping: 1"
also test the output message for ping_ack = false

2023-11-01 17:37 UTC, DarylDohner commented on EosLib/format/formats/ping_format.py
> +        self.ping_ack = ping_ack
i feel like it would be less confusing if this were self.ack

2023-11-01 17:37 UTC, DarylDohner commented on EosLib/format/formats/ping_format.py
> +class Ping(BaseFormat):
add docs to readme

2023-11-01 17:37 UTC, DarylDohner commented on tests/format/formats/test_ping_format.py
> +def get_ping_data_from_list(data_list: [int]):
the parameter makes no sense.  pick -- is good data list a global or are you going to pass as a param

2023-11-01 19:18 UTC, VanL15 submitted a review, later dismissed
See comment

2023-11-01 19:18 UTC, VanL15 commented on EosLib/format/formats/ping_format.py
> +            return "Received Ping: " + str(self.num)
I might be misreading this, but for the case `if self.ping_ack:`, shouldn't the return be `"Received ACK..."` rather than `"Received Ping..."? So basically, switch the return statements for the cases.

2023-11-01 19:34 UTC, aryanbattula commented on EosLib/format/formats/ping_format.py
> +            return "Received Ping: " + str(self.num)
im pretty sure self.ping_ack is for received ping, because we are saying here ping is true and ack is false

2023-11-02 20:07 UTC, DarylDohner approved these changes

2023-11-02 20:30 UTC, merged